### ISSUE TITLE
Checking version number, lol?

### ISSUE THREAD

**Issue by scriptzteam** [hoa00/S2U-Firewall-System#3]
$url=base64_decode("aHR0cDovL2FwcC5zMnUudm4vY2hlY2t1cGRhdGUucGhwP3Zlcj0=") -->

http://app.s2u.vn/checkupdate.php?ver= .... noope ur site is down ;)

**Comment by s2uteam** [comment]
Get the latest version of S.2.U Firewall System on https://www.facebook.com/groups/s2ufw/
